### ISSUE TITLE
Desktop & Documents widgets don't work

### ISSUE THREAD

**Issue by ofirgalcon** [tuxudo/icloud#4]
I see this in Report and listings, while the client tab correctly shows that some computers do have these enabled:

![image](https://user-images.githubusercontent.com/16665880/60353956-10245600-99c3-11e9-8f99-8bb6ba161fd6.png)

![image](https://user-images.githubusercontent.com/16665880/60354014-30541500-99c3-11e9-9ba9-459a88166a68.png)

**Comment by tuxudo** [comment]
The module is working as designed. If there is nothing set on the client, then the value is `null` in the database and not counted in the widget. Mobile documents is different than iCloud Desktop/Drive/Documents.
