### ISSUE TITLE
Module installed and activated but not appearing

### ISSUE THREAD

**Issue by opus-nbonenberger** [tuxudo/icloud#5]
I have installed the module with composer and activated it in `.env` with `icloud` but the install URL (script) does not mention icloud install steps. I verified that the installer script of MunkiReport is generated correctly by removing another module from `.env` and the module installation disappeared. So, why isn't icloud showing? In Module Manager in the MunkiReport backend it's listed as Installed and Active.

**Comment by tuxudo** [comment]
Do you see the icloud script in the generated client PKG? Do you see the iCloud listing?

**Comment by opus-nbonenberger** [comment]
In case you mean the installer created by the AutoPKG recipe:

I inspected the pkg with the Suspicious Package app and looked for the icloud script, not there. it's also not mentioned in the postflight script of the pkg. 

In case you did mean something else, please clarify.

**Comment by opus-nbonenberger** [comment]
@tuxudo can you look into this problem?

**Comment by tuxudo** [comment]
I'm not really able to look into this more at the moment due to work projects. I suggest asking in the #munkireport MacAdmins Slack channel.

**Comment by opus-nbonenberger** [comment]
forgot to set MODULE_SEARCH_PATH. Did not know that it needs to be set for every custom module. Closed.
